Repository iwa/Q-Bot, pull requests merged in 2020-05, with the labels that each got.

#19 v1.4
  .github/workflows/ci.yml
  README.md
  package.json
  src/commands/actions/highfive.ts
  src/commands/delembed.ts
  src/commands/delrole.ts
  src/commands/editembed.ts
  src/commands/games/flip.ts
  src/commands/games/roll.ts
  src/commands/games/rps.ts
  src/commands/memes/sonicsays.ts
  src/commands/profile/becomefan.ts
  src/commands/profile/leavefan.ts
  src/commands/profile/profile.ts
  src/commands/utility/anime.ts
  src/commands/utility/color.ts
  src/commands/utility/help.ts
  src/commands/utility/info.ts
  src/commands/utility/lead.ts
  src/commands/utility/leaderboard.ts
  src/commands/utility/manga.ts
  src/commands/utility/thanksiwa.ts
  src/index.ts
  src/js/actions.ts
  src/js/letmein.ts
  src/js/music.ts
  src/js/staff.ts
  src/js/starboard.ts
  src/js/utilities.ts
  views/level.ejs
  views/profile.ejs
  views/profileQumu.ejs
  views/sonicsays.ejs
  yarn.lock
Labels: update

#20 update highfive number gifs
  src/commands/actions/highfive.ts
Labels: update

#31 v1.4.2
  .github/workflows/ci.yml
  package.json
  src/utils/actions.ts
  src/utils/utilities.ts
  yarn.lock
Labels: update

#32 add funding links
  .github/FUNDING.yml
  .github/workflows/ci.yml
  src/utils/utilities.ts
Labels: update

#33 You missed a "d" at the end of "mute" at line 24
  src/events/messages/cooldown.ts
Labels: enhancement, prority: low

#34 chore: repair broken PRs
  src/events/messages/cooldown.ts
Labels: priority: high, update

#38 v1.4.3
  src/commands/profile/setbirthday.ts
  src/commands/utility/color.ts
  src/utils/utilities.ts
Labels: update

#41 v1.4.4
  package.json
  src/commands/actions/hifive.ts
  src/commands/memes/sonicsays.ts
  src/commands/profile/profile.ts
  src/utils/img.ts
  src/utils/leveling.ts
  src/utils/utilities.ts
  yarn.lock
Labels: update

#49 Apply fixes from CodeFactor
  src/commands/utility/color.ts
  src/commands/utility/help.ts
  src/events/messages/cooldown.ts
  src/index.ts
  src/utils/actions.ts
  src/utils/letmein.ts
Labels: enhancement

#50 v1.4.5 - add docs
  .github/workflows/ci.yml
  README-docs.md
  README.md
  docs/assets/css/main.css
  docs/assets/images/icons.png
  docs/assets/images/icons@2x.png
  docs/assets/images/widgets.png
  docs/assets/images/widgets@2x.png
  docs/assets/js/main.js
  docs/assets/js/search.json
  docs/classes/cooldowns.cooldown.html
  docs/classes/leveling.leveling-1.html
  docs/classes/reactionroles.reactionroles-1.html
  docs/classes/staff.staff-1.html
  docs/classes/starboard.starboard-1.html
  docs/classes/utilities.utilities-1.html
  docs/globals.html
  docs/index.html
  docs/interfaces/actions.stringkeyarray.html
  docs/interfaces/cooldowns.stringkeyarray.html
  docs/modules/actions.html
  docs/modules/birthdaycheck.html
  docs/modules/boostcolorcheck.html
  docs/modules/cooldowns.html
  docs/modules/highfivewatcher.html
  docs/modules/imgenerator.html
  docs/modules/letmein.html
  docs/modules/leveling.html
  docs/modules/memberleave.html
  docs/modules/music.html
  docs/modules/profile.html
  docs/modules/reactionroles.html
  docs/modules/readyfunction.html
  docs/modules/staff.html
  docs/modules/starboard.html
  docs/modules/subscount.html
  docs/modules/utilities.html
  package.json
  src/commands/utility/color.ts
  src/commands/utility/help.ts
  src/events/highfiveWatcher.ts
  src/events/memberLeave.ts
  src/events/messages/cooldown.ts
  src/events/reactionRoles.ts
  src/events/ready.ts
  src/events/starboard.ts
  src/index.ts
  src/loops/birthdayCheck.ts
  src/loops/boostColorCheck.ts
  src/loops/subsCount.ts
  src/utils/actions.ts
  src/utils/img.ts
  src/utils/letmein.ts
  src/utils/leveling.ts
  src/utils/music.ts
  src/utils/profile.ts
  src/utils/staff.ts
  src/utils/utilities.ts
  tsconfig.json
  yarn.lock
Labels: docs, update

#51 v1.4.6
  .github/workflows/ci.yml
  docs/classes/cooldowns.cooldown.html
  docs/classes/leveling.leveling-1.html
  docs/classes/reactionroles.reactionroles-1.html
  docs/classes/staff.staff-1.html
  docs/classes/starboard.starboard-1.html
  docs/classes/utilities.utilities-1.html
  docs/globals.html
  docs/index.html
  docs/interfaces/actions.stringkeyarray.html
  docs/interfaces/cooldowns.stringkeyarray.html
  docs/modules/actions.html
  docs/modules/birthdaycheck.html
  docs/modules/boostcolorcheck.html
  docs/modules/cooldowns.html
  docs/modules/highfivewatcher.html
  docs/modules/imgenerator.html
  docs/modules/letmein.html
  docs/modules/leveling.html
  docs/modules/memberleave.html
  docs/modules/music.html
  docs/modules/profile.html
  docs/modules/reactionroles.html
  docs/modules/readyfunction.html
  docs/modules/staff.html
  docs/modules/starboard.html
  docs/modules/subscount.html
  docs/modules/utilities.html
  package.json
Labels: bugfix, update

#55 Basic ?tronky command
  src/commands/actions/tronky.ts
  src/utils/actions.ts
Labels: feature

#57 add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#68 v1.5.2
  docs/classes/cooldowns.cooldown.html
  docs/classes/leveling.leveling-1.html
  docs/classes/reactionroles.reactionroles-1.html
  docs/classes/staff.staff-1.html
  docs/classes/starboard.starboard-1.html
  docs/classes/utilities.utilities-1.html
  docs/globals.html
  docs/index.html
  docs/interfaces/actions.stringkeyarray.html
  docs/interfaces/cooldowns.stringkeyarray.html
  docs/modules/actions.html
  docs/modules/birthdaycheck.html
  docs/modules/boostcolorcheck.html
  docs/modules/cooldowns.html
  docs/modules/highfivewatcher.html
  docs/modules/imgenerator.html
  docs/modules/letmein.html
  docs/modules/leveling.html
  docs/modules/memberleave.html
  docs/modules/music.html
  docs/modules/profile.html
  docs/modules/reactionroles.html
  docs/modules/readyfunction.html
  docs/modules/staff.html
  docs/modules/starboard.html
  docs/modules/subscount.html
  docs/modules/utilities.html
  package.json
  src/commands/actions/tronky.ts
Labels: bugfix
